import {
  PrivacyError,
  type Address,
  type OperationProgress,
  type PrivacyErrorKind,
  type PrivateBalance,
  type ProgressCallback,
  type RecipientStatus,
  type TxResult,
} from '../types.js';
import type {
  BatchWarning,
  Intent,
  PoolConfig,
  PreparedBatch,
  PrivacyOperations,
  SwapReview,
  WalletCapability,
} from '../operations.js';
import { protectedMinimumOut } from '../protected-minimum.js';

const STARK_FIELD_PRIME = (1n << 251n) + 17n * (1n << 192n) + 1n;

/**
 * A deterministic, in-memory `PrivacyOperations`.
 *
 * This exists so the Shell and World lanes can build and test every building
 * without a wallet, without mainnet, and without spending 6 STRK per action.
 * It is the thing that makes the mainnet-only decision (D-001) survivable.
 *
 * Deterministic on purpose: no clocks, no randomness, no network. Block height
 * only advances when a test says so. Two runs of the same script produce byte
 * identical results, which is what makes it usable in CI.
 *
 * It models the sharp edges rather than the happy path, because the happy path
 * is not what breaks:
 *   - notes are unspendable until they mature
 *   - operation value and the complete private fee are charged in their own tokens
 *   - the fee can change between prepare and confirm
 *   - the relay/gas estimate scales with the batch shape, never a constant
 *   - a shield cannot be batched with the transfer it funds
 *   - deposits are always to self
 */

export interface FakeConfig {
  /** Starting shielded balances, token → amount. */
  balances?: Record<Address, bigint>;
  /** Addresses registered in the pool and able to receive. */
  registered?: Address[];
  poolConfig?: Partial<PoolConfig>;
  capability?: Partial<WalletCapability>;
  /** Simulated latency in ms. Tests usually want 0. */
  latencyMs?: number;
  /** Explicit deterministic swap review inputs; never generated by the fake. */
  swapReview?: Omit<SwapReview, 'minimumAmountOut'>;
}

const DEFAULT_POOL: PoolConfig = {
  feeAmount: 6_000000000000000000n, // 6 STRK — the live mainnet value
  feeToken: '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d',
  proofValidityBlocks: 450,
  noteMaturityBlocks: 10,
};

/** Relay/gas cost the fake attributes to one pool-native spend action. */
const RELAY_FEE_PER_ACTION = 1_000000000000000n; // 1e15 — the single-spend baseline

/**
 * Deterministic relay/gas estimate for a prepared batch.
 *
 * This is a FIXTURE, not a fee oracle. The production adapter obtains this
 * number from the paymaster's relay estimate (see `estimateRelay` in
 * `wallet-api/operations.ts`), which scales with the on-chain work the batch
 * performs. We reproduce that shape-dependence deterministically: the estimate
 * grows with the number of spend actions and their kind — a private swap drives
 * an executor and mints an output note, strictly more work than a pool-native
 * transfer or unshield, so it counts double.
 *
 * It intentionally ignores the numeric amount — a larger felt is not more
 * calldata — so the estimate stays a predictable function of the batch *shape*
 * that consuming lanes can assert against. Shield-only batches pay no relay fee
 * here: their gas is the public deposit's own, outside the pool.
 *
 * The point of making this vary at all: a reserve or MAX computed against one
 * batch shape must be *detectably* wrong when spent on another. The previous
 * constant (`hasSpend ? 1e15 : 0`) was invariant to intent count, so it hid
 * exactly that class of bug — a stale gas quote reused across batch shapes.
 */
function estimateRelayFee(intents: readonly Intent[]): bigint {
  let units = 0n;
  for (const intent of intents) {
    if (intent.kind === 'shield') continue;
    units += intent.kind === 'swap' ? 2n : 1n;
  }
  return units * RELAY_FEE_PER_ACTION;
}

/** A fault the next matching call will raise. Consumed on use unless `sticky`. */
export interface Fault {
  kind: PrivacyErrorKind;
  /** Limit to one method. Omit to affect the next call of any kind. */
  on?: 'capability' | 'poolConfig' | 'balances' | 'recipientStatus' | 'prepare' | 'confirm';
  message?: string;
  sticky?: boolean;
}

interface MaturingNote {
  token: Address;
  amount: bigint;
  matureAtBlock: number;
}

export class FakePrivacyOperations implements PrivacyOperations {
  private spendable = new Map<Address, bigint>();
  private maturing: MaturingNote[] = [];
  private registeredAddrs: Set<string>;
  private pool: PoolConfig;
  private cap: WalletCapability;
  private faults: Fault[] = [];
  private latency: number;
  private block = 0;
  private txCounter = 0;
  private readonly configuredSwapReview?: Omit<SwapReview, 'minimumAmountOut'>;

  /** Every confirmed batch, in order. Assert against this in tests. */
  readonly submitted: Intent[][] = [];

  constructor(config: FakeConfig = {}) {
    for (const [token, amount] of Object.entries(config.balances ?? {})) {
      try {
        if (BigInt(token) === 0n) throw new Error();
        normalise(token);
      } catch {
        throw new PrivacyError('unknown', 'The fake starting balance token is invalid.');
      }
      if (typeof amount !== 'bigint' || amount < 0n) {
        throw new PrivacyError('unknown', 'The fake starting balance amount must be a non-negative bigint.');
      }
      this.spendable.set(token, amount);
    }
    this.registeredAddrs = new Set((config.registered ?? []).map((address) => {
      let value: bigint;
      try {
        value = BigInt(address);
      } catch {
        throw new PrivacyError('unknown', 'The fake registered recipient is invalid.');
      }
      if (value <= 0n) {
        throw new PrivacyError('unknown', 'The fake registered recipient is invalid.');
      }
      return normalise(address);
    }));
    this.pool = { ...DEFAULT_POOL, ...config.poolConfig };
    let feeTokenValue: bigint;
    try {
      feeTokenValue = BigInt(this.pool.feeToken);
    } catch {
      throw new PrivacyError('unknown', 'The fake pool fee configuration is invalid.');
    }
    if (
      typeof this.pool.feeAmount !== 'bigint'
      || this.pool.feeAmount < 0n
      || feeTokenValue <= 0n
    ) {
      throw new PrivacyError('unknown', 'The fake pool fee configuration is invalid.');
    }
    if (
      !Number.isSafeInteger(this.pool.noteMaturityBlocks)
      || this.pool.noteMaturityBlocks < 0
      || !Number.isSafeInteger(this.pool.proofValidityBlocks)
      || this.pool.proofValidityBlocks <= 0
    ) {
      throw new PrivacyError('unknown', 'The fake pool config has invalid lifecycle block windows.');
    }
    this.cap = {
      supportsStrk20: true,
      walletApiVersion: '0.10.3',
      registration: 'registered',
      ...config.capability,
    };
    if (
      typeof this.cap.supportsStrk20 !== 'boolean'
      || (this.cap.walletApiVersion !== null && typeof this.cap.walletApiVersion !== 'string')
      || !['registered', 'unregistered', 'unknown'].includes(this.cap.registration)
    ) {
      throw new PrivacyError('unknown', 'The fake capability configuration is invalid.');
    }
    const latency = config.latencyMs ?? 0;
    if (!Number.isSafeInteger(latency) || latency < 0) {
      throw new PrivacyError('unknown', 'The fake latency must be a non-negative safe integer.');
    }
    this.latency = latency;
    if (config.swapReview !== undefined) {
      if (!Number.isSafeInteger(config.swapReview.expiresAt) || config.swapReview.expiresAt <= 0) {
        throw new PrivacyError('unknown', 'The deterministic swap review is invalid.');
      }
      try {
        protectedMinimumOut(config.swapReview.expectedAmountOut, config.swapReview.slippageBps);
      } catch {
        throw new PrivacyError('unknown', 'The deterministic swap review is invalid.');
      }
      this.configuredSwapReview = Object.freeze({ ...config.swapReview });
    }
  }

  // -- test controls --------------------------------------------------------

  /** Make the next matching call fail. */
  injectFault(fault: Fault): void {
    this.faults.push(Object.freeze({ ...fault }));
  }

  /** Advance the chain. Matures any notes whose time has come. */
  advanceBlocks(n: number): void {
    if (!Number.isSafeInteger(n) || n < 0) {
      throw new PrivacyError('unknown', 'The block advance must be a non-negative safe integer.');
    }
    this.block += n;
    const stillMaturing: MaturingNote[] = [];
    for (const note of this.maturing) {
      if (note.matureAtBlock <= this.block) {
        this.credit(note.token, note.amount);
      } else {
        stillMaturing.push(note);
      }
    }
    this.maturing = stillMaturing;
  }

  /**
   * Change the pool fee mid-flight.
   *
   * The real fee is governance-settable and has already moved once, so a
   * batch prepared at one fee can be confirmed at another. `confirm` must
   * reject when that breaches the ceiling — this is how you test it.
   */
  setPoolFee(feeAmount: bigint): void {
    if (typeof feeAmount !== 'bigint' || feeAmount < 0n) {
      throw new PrivacyError('unknown', 'The fake pool fee must be a non-negative bigint.');
    }
    this.pool = { ...this.pool, feeAmount };
  }

  get currentBlock(): number {
    return this.block;
  }

  // -- PrivacyOperations ----------------------------------------------------

  async capability(signal?: AbortSignal): Promise<WalletCapability> {
    await this.tick('capability', signal);
    return Object.freeze({ ...this.cap });
  }

  async poolConfig(signal?: AbortSignal): Promise<PoolConfig> {
    await this.tick('poolConfig', signal);
    return { ...this.pool };
  }

  async balances(tokens?: Address[], signal?: AbortSignal): Promise<PrivateBalance[]> {
    const requestedTokens = tokens === undefined ? undefined : [...tokens];
    await this.tick('balances', signal);
    const keys = requestedTokens?.length
      ? requestedTokens
      : [...new Set([...this.spendable.keys(), ...this.maturing.map((n) => n.token)])];
    return keys.map((token) => {
      const spendable = this.spendable.get(token) ?? 0n;
      const maturing = this.maturing
        .filter((n) => sameAddress(n.token, token))
        .reduce((sum, n) => sum + n.amount, 0n);
      return { token, spendable, maturing, total: spendable + maturing, maturityKnown: true };
    });
  }

  async recipientStatus(address: Address, signal?: AbortSignal): Promise<RecipientStatus> {
    assertAddress(address, 'fake recipient');
    await this.tick('recipientStatus', signal);
    return this.registeredAddrs.has(normalise(address)) ? 'registered' : 'unregistered';
  }

  async prepare(intents: Intent[], signal?: AbortSignal): Promise<PreparedBatch> {
    // Own the intents synchronously, before the first await, exactly as the
    // Wallet API implementation does — its own capture sits after a sync
    // `throwIfAborted` and before anything awaited. `tick()` is async, so
    // awaiting it first would yield a microtask even at zero latency and let a
    // caller mutate its array between the unawaited `prepare()` call and the
    // settled promise. A double that captures later grants a freedom
    // production does not.
    const reviewed = freezeIntents(intents);
    await this.tick('prepare', signal);
    if (reviewed.length === 0) {
      throw new PrivacyError('unknown', 'prepare called with no intents');
    }
    for (const intent of reviewed) {
      const amount = intent.kind === 'swap' ? intent.amountIn : intent.amount;
      if (amount <= 0n) throw new PrivacyError('unknown', 'Amounts must be positive.');
      assertAddress(intent.kind === 'swap' ? intent.tokenIn : intent.token, 'fake intent token');
      if (intent.kind === 'swap' && intent.minAmountOut <= 0n) {
        throw new PrivacyError('unknown', 'Minimum output must be positive.');
      }
      if (intent.kind === 'swap') assertAddress(intent.tokenOut, 'fake swap output token');
      if (intent.kind === 'unshield' || intent.kind === 'transfer') {
        assertAddress(intent.recipient, 'fake intent recipient');
      }
    }

    const warnings: BatchWarning[] = [];
    const feeAtPrepare = this.pool.feeAmount;

    // A shield cannot ride along with the transfer it funds: the deposit's
    // public leg names the depositor, so bundling publishes the link.
    const hasShield = reviewed.some((i) => i.kind === 'shield');
    const hasSpend = reviewed.some((i) => i.kind !== 'shield');
    if (hasShield && hasSpend) {
      throw new PrivacyError(
        'privacy-leak',
        'Shielding and private spending must be prepared as separate operations.',
      );
    }
    const kinds = new Set(reviewed.map((intent) => intent.kind));
    if (!hasShield && kinds.size > 1) {
      throw new PrivacyError('unknown', 'A private batch may contain only one approved route type.');
    }
    if (kinds.has('swap') && reviewed.length > 1) {
      throw new PrivacyError('unknown', 'A private swap must be prepared one at a time.');
    }
    const promptCount = 1;

    for (const intent of reviewed) {
      if (intent.kind === 'shield') {
        warnings.push({
          kind: 'public-leg',
          detail: `Depositing ${intent.amount} is public: the amount and your address are visible on-chain.`,
        });
      }
      if (intent.kind === 'unshield') {
        warnings.push({
          kind: 'public-leg',
          detail: `Withdrawing reveals the amount and ${intent.recipient} on-chain.`,
        });
      }
      if (intent.kind === 'transfer' && !this.registeredAddrs.has(normalise(intent.recipient))) {
        throw new PrivacyError(
          'not-registered',
          'The recipient is not registered with the privacy pool.',
        );
      }
    }

    // Deterministic, and a function of the batch shape — not a constant.
    const relayFee = estimateRelayFee(reviewed);

    // Charge spends in their own token and both private fees in the fee token.
    const spendByToken = new Map<string, bigint>();
    for (const intent of reviewed) {
      if (intent.kind === 'shield') continue;
      const token = intent.kind === 'swap' ? intent.tokenIn : intent.token;
      const amount = intent.kind === 'swap' ? intent.amountIn : intent.amount;
      spendByToken.set(normalise(token), (spendByToken.get(normalise(token)) ?? 0n) + amount);
    }
    if (hasSpend) {
      const feeToken = normalise(this.pool.feeToken);
      spendByToken.set(
        feeToken,
        (spendByToken.get(feeToken) ?? 0n) + feeAtPrepare + relayFee,
      );
    }
    for (const [token, required] of spendByToken) {
      const have = this.spendable.get(token) ?? this.lookupLoose(token);
      const remaining = have - required;
      if (remaining < 0n) {
        throw new PrivacyError(
          'insufficient-balance',
          `Needs ${required}, has ${have}. Remember the pool fee is paid in ${this.pool.feeToken}.`,
        );
      }
      if (sameAddress(token, this.pool.feeToken) && remaining < feeAtPrepare + relayFee) {
        warnings.push({ kind: 'leaves-below-fee', remaining, feeEstimate: feeAtPrepare + relayFee });
      }
    }

    const maturingTotal = this.maturing.reduce((s, n) => s + n.amount, 0n);
    if (maturingTotal > 0n) {
      const soonest = Math.min(...this.maturing.map((n) => n.matureAtBlock));
      warnings.push({
        kind: 'funds-maturing',
        maturingAmount: maturingTotal,
        blocksRemaining: Math.max(0, soonest - this.block),
      });
    }

    const gasEstimate = relayFee;
    const { intents: canonicalIntents, swapReview } = this.canonicalizeIntents(reviewed);
    const publishedWarnings = freezeWarnings(warnings);
    const self = this;
    let discarded = false;
    let confirmationAttempted = false;

    return {
      // The frozen snapshot itself: one owner for the published view, the
      // recorded submission and the balance arithmetic.
      intents: canonicalIntents,
      poolFee: feeAtPrepare,
      gasEstimate,
      totalCost: feeAtPrepare + gasEstimate,
      warnings: publishedWarnings,
      promptCount,
      ...(swapReview === undefined ? {} : { swapReview }),
      async confirm({ feeCeiling, onProgress, signal: sig }) {
        if (discarded) throw new PrivacyError('unknown', 'batch already discarded');
        assertFeeCeilingInput(feeCeiling);
        if (confirmationAttempted) {
          throw new PrivacyError('unknown', 'This batch was already confirmed or attempted. Prepare a new batch.');
        }
        confirmationAttempted = true;
        await self.tick('confirm', sig);
        if (discarded) throw new PrivacyError('unknown', 'batch already discarded');

        // The fee can move between prepare and confirm. This is the guard.
        const currentFee = self.pool.feeAmount + relayFee;
        if (currentFee > feeCeiling) {
          throw new PrivacyError(
            'unknown',
            `Private fee is now ${currentFee}, above the ceiling of ${feeCeiling}. Re-prepare.`,
          );
        }

        emitProgress(onProgress, { stage: 'awaiting-approval', message: 'Confirm in your wallet' });
        emitProgress(onProgress, { stage: 'proving', message: 'Your wallet is generating a proof' });
        emitProgress(onProgress, { stage: 'submitting', message: 'Submitting' });

        self.applyIntents(canonicalIntents, currentFee);
        self.submitted.push([...canonicalIntents]);
        emitProgress(onProgress, { stage: 'done', message: 'Done' });
        return { transactionHash: `0xfake${(++self.txCounter).toString(16).padStart(4, '0')}` };
      },
      discard() {
        discarded = true;
      },
    };
  }

  // -- internals ------------------------------------------------------------

  private canonicalizeIntents(intents: readonly Intent[]): {
    intents: readonly Intent[];
    swapReview?: SwapReview;
  } {
    const configured = this.configuredSwapReview;
    const intent = intents.length === 1 && intents[0]?.kind === 'swap' ? intents[0] : undefined;
    if (!configured || !intent) return { intents };
    if (!Number.isSafeInteger(configured.expiresAt) || configured.expiresAt <= 0) {
      throw new PrivacyError('unknown', 'The deterministic swap review is invalid.');
    }
    const protectedMinimum = protectedMinimumOut(configured.expectedAmountOut, configured.slippageBps);
    if (protectedMinimum < intent.minAmountOut) {
      throw new PrivacyError('unknown', 'The requested swap floor exceeds the protected minimum.');
    }
    const canonicalIntent: Intent = Object.freeze({ ...intent, minAmountOut: protectedMinimum });
    return {
      intents: Object.freeze([canonicalIntent]),
      swapReview: Object.freeze({
        expectedAmountOut: configured.expectedAmountOut,
        minimumAmountOut: canonicalIntent.minAmountOut,
        slippageBps: configured.slippageBps,
        expiresAt: configured.expiresAt,
      }),
    };
  }

  private applyIntents(intents: readonly Intent[], fee: bigint): void {
    let feeCharged = false;
    for (const intent of intents) {
      switch (intent.kind) {
        case 'shield':
          // Always to self, and not spendable until it matures.
          this.maturing.push({
            token: intent.token,
            amount: intent.amount,
            matureAtBlock: this.block + this.pool.noteMaturityBlocks,
          });
          break;
        case 'unshield':
        case 'transfer':
          this.debit(intent.token, intent.amount);
          break;
        case 'swap':
          this.debit(intent.tokenIn, intent.amountIn);
          this.maturing.push({
            token: intent.tokenOut,
            amount: intent.minAmountOut,
            matureAtBlock: this.block + this.pool.noteMaturityBlocks,
          });
          break;
      }
      if (!feeCharged && intent.kind !== 'shield') {
        this.debit(this.pool.feeToken, fee);
        feeCharged = true;
      }
    }
  }

  private lookupLoose(token: string): bigint {
    for (const [key, value] of this.spendable) {
      if (sameAddress(key, token)) return value;
    }
    return 0n;
  }

  private credit(token: Address, amount: bigint): void {
    for (const key of this.spendable.keys()) {
      if (sameAddress(key, token)) {
        this.spendable.set(key, (this.spendable.get(key) ?? 0n) + amount);
        return;
      }
    }
    this.spendable.set(token, amount);
  }

  private debit(token: Address, amount: bigint): void {
    for (const key of this.spendable.keys()) {
      if (sameAddress(key, token)) {
        this.spendable.set(key, (this.spendable.get(key) ?? 0n) - amount);
        return;
      }
    }
    this.spendable.set(token, -amount);
  }

  private async tick(method: Fault['on'], signal?: AbortSignal): Promise<void> {
    if (signal?.aborted) throw new PrivacyError('user-rejected', 'aborted');
    if (this.latency > 0) {
      await new Promise((resolve) => setTimeout(resolve, this.latency));
      if (signal?.aborted) throw new PrivacyError('user-rejected', 'aborted');
    }
    const index = this.faults.findIndex((f) => !f.on || f.on === method);
    if (index >= 0) {
      const fault = this.faults[index]!;
      if (!fault.sticky) this.faults.splice(index, 1);
      throw new PrivacyError(fault.kind, fault.message ?? `injected fault: ${fault.kind}`);
    }
  }
}

/**
 * Take ownership of the intents a caller asked for; see the identically named
 * helper in `wallet-api/operations.ts`. `Intent` is flat, so one level of
 * copy-and-freeze is a full deep freeze.
 */
function freezeIntents(intents: readonly Intent[]): readonly Intent[] {
  return Object.freeze(intents.map((intent) => Object.freeze({ ...intent })));
}

/** Match production's immutable review disclosure boundary. */
function freezeWarnings(warnings: readonly BatchWarning[]): readonly BatchWarning[] {
  return Object.freeze(warnings.map((warning) => Object.freeze({ ...warning })));
}

/**
 * Addresses arrive padded and unpadded. Never compare with `===`.
 *
 * Keeps the `0x` prefix so the result is still parseable by `BigInt` — an
 * earlier version returned a bare hex string, which made every downstream
 * comparison silently fall back to string equality.
 */
function normalise(address: string): string {
  return `0x${BigInt(address).toString(16)}`;
}

function assertAddress(address: unknown, label: string): asserts address is Address {
  if (typeof address !== 'string' || !/^0x[0-9a-fA-F]+$/.test(address)) {
    throw new PrivacyError('unknown', `Invalid ${label} address.`);
  }
  let value: bigint;
  try { value = BigInt(address); } catch { throw new PrivacyError('unknown', `Invalid ${label} address.`); }
  if (value <= 0n || value >= STARK_FIELD_PRIME) {
    throw new PrivacyError('unknown', `Invalid ${label} address.`);
  }
}

function sameAddress(a: string, b: string): boolean {
  try {
    return BigInt(a) === BigInt(b);
  } catch {
    return a === b;
  }
}

function emitProgress(callback: ProgressCallback | undefined, progress: OperationProgress): void {
  try {
    callback?.(Object.freeze({ ...progress }));
  } catch {
    /* Observers cannot alter a financial operation. */
  }
}

function assertFeeCeilingInput(ceiling: unknown): asserts ceiling is bigint {
  if (typeof ceiling !== 'bigint' || ceiling < 0n) {
    throw new PrivacyError('unknown', 'The fee ceiling must be a non-negative bigint.');
  }
}
