/**
 * The tokens the Vault can lend, in order, with the display metadata the
 * counter shows (D-079, D-081): each token's symbol and decimals as its
 * contract reported them at generation, its group in the picker, and the
 * Vesu pool its vault supplies into.
 *
 * Generated by `scripts/vesu-markets.mjs` from `scripts/vesu-markets.json`
 * (D-081). Do not edit by hand: `node scripts/vesu-markets.mjs --write`
 * re-derives the list from Vesu's API, re-verifies every entry on mainnet
 * and rewrites this file, and `scripts/vesu-markets.test.mjs` fails on any
 * hand edit.
 */

export type VaultMarketGroup = 'majors' | 'stables' | 'btc' | 'staking' | 'ecosystem';

/** The picker's groups, in order. */
export const VAULT_MARKET_GROUPS: readonly VaultMarketGroup[] = ['majors', 'stables', 'btc', 'staking', 'ecosystem'];

/** One market as the counter describes it. */
export interface VaultMarketMetadata {
  readonly token: string;
  readonly symbol: string;
  readonly decimals: number;
  readonly group: VaultMarketGroup;
  readonly poolName: string;
  readonly curation: 'prime' | 'curated';
}

export const VAULT_MARKET_METADATA: readonly VaultMarketMetadata[] = [
  { token: '0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d', symbol: 'STRK', decimals: 18, group: 'majors', poolName: 'Prime', curation: 'prime' },
  { token: '0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7', symbol: 'ETH', decimals: 18, group: 'majors', poolName: 'Prime', curation: 'prime' },
  { token: '0x033068f6539f8e6e6b131e6b2b814e6c34a5224bc66947c47dab9dfee93b35fb', symbol: 'USDC', decimals: 6, group: 'stables', poolName: 'Prime', curation: 'prime' },
  { token: '0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8', symbol: 'USDT', decimals: 6, group: 'stables', poolName: 'Prime', curation: 'prime' },
  { token: '0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8', symbol: 'USDC.e', decimals: 6, group: 'stables', poolName: 'Prime', curation: 'prime' },
  { token: '0x03fe2b97c1fd336e750087d68b9b867997fd64a2661ff3ca5a7c771641e8e7ac', symbol: 'WBTC', decimals: 8, group: 'btc', poolName: 'Prime', curation: 'prime' },
  { token: '0x0787150e306e6eae6e3f79dea881770e8bbff2c1b8eb490f969669ee945b3135', symbol: 'strkBTC', decimals: 8, group: 'btc', poolName: 'Re7 xBTC', curation: 'curated' },
  { token: '0x04daa17763b286d1e59b97c283c0b8c949994c361e426a28f743c67bdfe9a32f', symbol: 'tBTC', decimals: 18, group: 'btc', poolName: 'Re7 xBTC', curation: 'curated' },
  { token: '0x0593e034dda23eea82d2ba9a30960ed42cf4a01502cc2351dc9b9881f9931a68', symbol: 'SolvBTC', decimals: 18, group: 'btc', poolName: 'Re7 xBTC', curation: 'curated' },
  { token: '0x028d709c875c0ceac3dce7065bec5328186dc89fe254527084d1689910954b0a', symbol: 'xSTRK', decimals: 18, group: 'staking', poolName: 'Prime', curation: 'prime' },
  { token: '0x0057912720381af14b0e5c87aa4718ed5e527eab60b3801ebf702ab09139e38b', symbol: 'wstETH', decimals: 18, group: 'staking', poolName: 'Prime', curation: 'prime' },
  { token: '0x06a567e68c805323525fe1649adb80b03cddf92c23d2629a6779f54192dffc13', symbol: 'xWBTC', decimals: 8, group: 'staking', poolName: 'Prime', curation: 'prime' },
  { token: '0x047751b3532fabca89b0f2e35ca1cb45e5a7b11d5e3d3663dfa1f4406b45fd88', symbol: 'xstrkBTC', decimals: 8, group: 'staking', poolName: 'Re7 xBTC', curation: 'curated' },
  { token: '0x043a35c1425a0125ef8c171f1a75c6f31ef8648edcc8324b55ce1917db3f9b91', symbol: 'xtBTC', decimals: 18, group: 'staking', poolName: 'Re7 xBTC', curation: 'curated' },
  { token: '0x036834a40984312f7f7de8d31e3f6305b325389eaeea5b1c0664b2fb936461a4', symbol: 'LBTC', decimals: 8, group: 'staking', poolName: 'Re7 xBTC', curation: 'curated' },
  { token: '0x075afe6402ad5a5c20dd25e10ec3b3986acaa647b77e4ae24b0cbc9a54a27a87', symbol: 'EKUBO', decimals: 18, group: 'ecosystem', poolName: 'Re7 Labs Starknet Ecosystem', curation: 'curated' },
];
